### ISSUE TITLE
Increase the flag name limit from 45 chars to at least 1024 chars (the DB field and UI with possible truncation)

### ISSUE THREAD

**Issue by vlad-ko** [codecov/feedback#148]
A prospective customer uses complex package name (paths) to convert them into flags. Our current limit of 45 chars is an eventual blocker issue. 

Proposal: increase DB field size and API validation (as well as other processing layers) to support 1024 chars. The customer doesn't intend to use the full size, with most flags likely being around 200 chars. However, since we are making the change let's make it future proof. 

Some items to consider:
- Github PR comment can only support so many chars (tested with 100), without the flag table looking misaligned. 
- In the Codecov UI, the "Uploads" sections is too small. A flags with 50+ chars in the name will be pushing the "box" beyond the limits. Suggestion: convert this section to a modal that can fill most of the screen.
- Flags drop down for selecting/searching needs to be able to support a larger number of chars
- In some cases (such as the drop-down) the UI truncation of the beginning characters (ending is likely to be the most unique part) is acceptable to preserve aesthetics and functionality 
- URL query string length has to be able to accept larger number of chars + other params

Additional important request:
- Allow "special chars" such as `;` to be allowed in the flag name. (URL encode special chars, required for complex names)

**Comment by vlad-ko** [comment]
After testing, it seems to fail (at least at first) during the upload. Need to take a look if there's validation on the upload endpoint.

**Comment by chris-mitchell** [comment]
Thanks for posting this @vlad-ko.  Let us know if there is anything else we can test or any other info we can provide to the team.

**Comment by vlad-ko** [comment]
One blocking validation needs to be relaxed here: https://github.com/codecov/shared/blob/9802cb57362193cc1d96bbadd649bbf1417ce50f/shared/validation/user_schema.py#L1

**Comment by vlad-ko** [comment]
this was done
