### ISSUE TITLE
Header of the PR comment doesn't match the "diff table" with detailed info

### ISSUE THREAD

**Issue by vlad-ko** [codecov/feedback#394]
In the PR comment we say that there are 5 lines missing. This is also visible in the UI. (49, 50, 51, 52, 53) 

![Screenshot 2024-05-30 at 9 35 33 AM](https://github.com/codecov/feedback/assets/27556/7d3c9c2e-7b91-4350-ba4c-5bff1d6fd7de)

However, if we look at the table, where we show the breakdown by line, we say that there are 4 "missed" lines. 

![Screenshot 2024-05-30 at 9 28 13 AM](https://github.com/codecov/feedback/assets/27556/afd8154e-07de-44cb-86fb-916a5229c63f)

**Comment by tnt-sentry** [comment]
@vlad-ko is this happening consistently? This is pretty stale so if it was a one off, it would be best to reopen when/if it happens again.
