### ISSUE TITLE
`Missing Base Commit` and `build code not found` messages for commits/PRs

### ISSUE THREAD

**Issue by LiranCohen** [codecov/feedback#436]
**Describe the bug**
When CI uploads coverage reports to Codecov, everything looks as expected in the CI output, without any errors, however when visiting the Codecov PR/Commit I am met with a mssage `Missing Base Commit` and no data displayed.

On the commits themselves I also see a `build code not found` error on the right side where it should list the uploads.

This is happening for any PR that is opened.

I've tried to upload manually through the CLI and still have the same results.

**Screenshots**
![Screenshot 2024-06-20 at 4 55 36 PM](https://github.com/codecov/feedback/assets/2191517/87776fc5-5a5e-427c-8d00-77b4bdf70b89)

![Screenshot 2024-06-20 at 4 56 16 PM](https://github.com/codecov/feedback/assets/2191517/5a4a98ad-d61c-4f29-b957-2b70a8d83295)

**Additional context**
I noticed in the debug output I see `parent_commit_id` set to `null`:
```
debug - 2024-06-20 20:33:14,108 -- Commit creating result --- {"result": "RequestResult(error=None, warnings=[], status_code=201, text='{\"message\":null,\"timestamp\":\"2024-06-20T20:33:14.059840Z\",\"ci_passed\":null,\"state\":null,\"repository\":{\"name\":\"dwn-sdk-js\",\"is_private\":false,\"active\":true,\"language\":null,\"yaml\":{\"ignore\":[\"^src/types.*\"],\"coverage\":{\"status\":{\"project\":{\"default\":{\"target\":\"auto\"}}}}}},\"author\":null,\"commitid\":\"18069cd29b99fcbe1990aaeb6d3920130e24ecc7\",\"parent_commit_id\":null,\"pullid\":762,\"branch\":\"lirancohen/events-query-by-protocol\"}')"}
```

I've also noticed the `last commit` on the main branch in Codecov is different from the one in git.
![Screenshot 2024-06-20 at 4 59 49 PM](https://github.com/codecov/feedback/assets/2191517/2719a059-67a0-4b96-b6a8-1d7ce1f1d354)
![Screenshot 2024-06-20 at 5 00 10 PM](https://github.com/codecov/feedback/assets/2191517/108b36ff-c83f-4659-85c0-ae216a1e6dc2)

the project is open source so you can see the workflow files as well as the codecov status:
https://github.com/TBD54566975/dwn-sdk-js
https://app.codecov.io/github/TBD54566975/dwn-sdk-js

**Comment by nihui** [comment]
Same issue here for our opensource project

see https://app.codecov.io/gh/Tencent/ncnn/commit/fbd6690d6cb2c5db91658d937b77faee51b5cdc3

We haven't adjusted the codecov configuration, and it doesn't work recently.
We use the codecov github action

**Comment by LiranCohen** [comment]
This seems to have fixed itself for my repo this AM, how about you @nihui?
