### ISSUE TITLE
Coverage lines on pull requests are incorrect

### ISSUE THREAD

**Issue by MetRonnie** [codecov/feedback#556]
**Describe the bug**

When a GitHub Actions workflow runs on the `pull_request` event, `actions/checkout` by default does not check out the pull request branch itself, but merges it into the base branch and checks out this merge commit.

This means that the reported coverage is for this merge commit, but the Codecov website does not account for this. When you view the coverage for a PR on the Codecov website, it shows the files as they are in the PR branch, meaning the coverage lines are incorrect (when there have been other changes to the same files committed to the base branch).

**Environment (please complete the following information):**
 - Browser N/A
 - System N/A

**To Reproduce**
1. Look at https://app.codecov.io/gh/cylc/cylc-flow/pull/6445/blob/cylc/flow/task_pool.py#L879 (screenshot below)
2. Note that a different PR was merged into the base branch in between the base & head commits for this PR: https://github.com/cylc/cylc-flow/commit/fb75928e688c9f4d79e1850d85598cbf12c2c752#diff-becd22b70a92532763c24d9e0bedde95e36801c2eac01a469939f006c2faa148R880

**Expected behavior**
I guess the only solution is for the Codecov website to display the same internal merge commit that `actions/checkout` checked out, rather than the head commit of the PR

**Screenshots**

Here the coverage lines start to go wrong at L880 - executable lines are shown as unexecutable and vice versa!

![Image](https://github.com/user-attachments/assets/b8ceb42b-886e-40b6-94cd-8447b56a2b4e)

Here is the commit graph. The highlighted merge commit added some lines at L880 to the same file.

![Image](https://github.com/user-attachments/assets/7eefc3c3-1312-4c44-8036-adb3769f974d)

Here is that merge commit.

![Image](https://github.com/user-attachments/assets/0ea2e30c-90f0-4d0e-8892-29ac1da35bbe)

**Additional context**
Here is the GitHub Actions workflow for this repo: https://github.com/cylc/cylc-flow/blob/2f495817a19f09f4ed12aa6a00162a2923b291eb/.github/workflows/test_fast.yml

**Comment by michelletran-sentry** [comment]
Sorry for the delay in responding. @MetRonnie It looks like the linked issue is no longer inconsistent. I suspect that the problem was related to the coverage report still being processed when accessing the webpage. We are working on a longer term solution in this issue: https://github.com/codecov/engineering-team/issues/2702

**Comment by MetRonnie** [comment]
You're right that the coverage I linked is now correct, as it includes the few lines added on the base branch by my colleague. However I think this is because I rebased and force-pushed the branch after opening this issue

![Image](https://github.com/user-attachments/assets/7dc975dc-0910-4299-b664-fd4c19d06b6b)

**Comment by michelletran-sentry** [comment]
It sounds like rebasing solved the issue for this PR. The larger systemic issue is still likely related to a lag in coverage reporting (as linked in a ticket above) or coverage processing failures. Closing this as it is no longer an issue for the linked issue. If you run into this issue again, feel free to create a new ticket.
