### ISSUE TITLE
Feature Request: Enable User Activation/Deactivation via API

### ISSUE THREAD

**Issue by vlad-ko** [codecov/feedback#559]
Currently, there is no method to activate or deactivate users programmatically through the API; this action can only be completed manually in the UI. This manual process is time-consuming and inefficient for users who prefer to manage user states programmatically, especially in large organizations.

Request:
Add support for `PUT` and `DELETE` methods on the API user detail endpoint to allow for activation and deactivation of users.

**Use Case Examples:**

**Deactivation after Role Changes:**
- If a user is deactivated in an identity management system (e.g., Okta), the organization would like the ability to disable the same user in our system through a simple API call, instead of manually logging into the UI.

**Adjusting User Access after Privilege Changes:**
- When a user is moved to a different team or position, organizations may want to remove them from Codecov while they still remain active in GitHub or another SSO provider. Right now, this requires manually logging in, finding the organization, and deactivating the user one at a time.

This API enhancement would significantly streamline user management for our customers, allowing them to maintain accurate access control in alignment with their internal processes.

**Comment by JerrySentry** [comment]
@vlad-ko I'm thinking instead of PUT and DELETE, we will use PATCH and having a request payload like so `{activated: boolean}`. This aligns better with our existing API conventions.

**Comment by JerrySentry** [comment]
New endpoint here: https://docs.codecov.com/reference/users_partial_update
