### ISSUE TITLE
Is there a way to run self-hosted codecov on port 80?

### ISSUE THREAD

**Issue by 0golovatyi** [codecov/feedback#75]
**What product do you want to improve?**
Self-hosted

**Is your feature request related to a problem? Please describe.**
I am trying to get Let's Encrypt certificate for my self-hosted codecov, but it only issues for server running on port 80. When I do redirect (via load-balancer rules) certbot recognizes it and fails.

**Describe the solution you'd like**
If I can just run self-hosted codecov on port 80.

**Comment by LeoQuote** [comment]
Normally codecov would be behind of proxy like nginx or Apache, it should be easy to setup the proxy instead of codecov the application
